FPS = 60

LARGE_FONT_SIZE = 80

FONT_PATH = "./assets/Vollkorn-VariableFont_wght.ttf"

# --- Title Screen Constants ---
TITLE_SCREEN_TEXT_Y_POSITION = 0.30
TITLE_SCREEN_BUTTON_HEIGHT = 60
TITLE_SCREEN_BUTTON_WIDTH = 250
TITLE_SCREEN_BUTTON_Y_POSITION = 0.5
TITLE_SCREEN_BUTTON_PADDING = 25
TITLE_SCREEN_TITLE_RECT_X = .20
TITLE_SCREEN_TITLE_RECT_Y = .15
TITLE_SCREEN_TITLE_RECT_WIDTH = .6
TITLE_SCREEN_TITLE_RECT_HEIGHT = .3

# --- Welcome Screen Constants ---
WELCOME_SCREEN_TEXT_RECT_X = 0.05
WELCOME_SCREEN_TEXT_RECT_Y = 0.06
WELCOME_SCREEN_TEXT_RECT_Y_PADDING = 0.05
WELCOME_SCREEN_WELCOME_MESSAGE_FONT_SIZE = 22
WELCOME_SCREEN_BUTTON_HEIGHT = 60
WELCOME_SCREEN_BUTTON_WIDTH = 280
WELCOME_SCREEN_BUTTON_X_POSITION = 0.5
WELCOME_SCREEN_BUTTON_Y_POSITION = 0.86
WELCOME_SCREEN_BUTTON_PADDING = 0.06
WELCOME_SCREEN_BUTTON_FONT_SIZE = 25

# --- Character Creation Screen Constants ---
CHARACTER_CREATION_SCREEN_DIVIDER_LINE_ONE_STARTING_X = 0.17
CHARACTER_CREATION_SCREEN_DIVIDER_LINE_ONE_STARTING_Y = 0
CHARACTER_CREATION_SCREEN_DIVIDER_LINE_ONE_ENDING_X = 0.17
CHARACTER_CREATION_SCREEN_DIVIDER_LINE_TWO_STARTING_X = 0.17
CHARACTER_CREATION_SCREEN_DIVIDER_LINE_TWO_STARTING_Y = 0.16
CHARACTER_CREATION_SCREEN_DIVIDER_LINE_TWO_ENDING_Y = 0.16
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_STARTING_X = 0
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_STARTING_Y = 0
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_WIDTH = 0.17
CHARACTER_CREATION_SCREEN_PHASE_TITLE_PANEL_STARTING_X = 0.17
CHARACTER_CREATION_SCREEN_PHASE_TITLE_PANEL_STARTING_Y = 0
CHARACTER_CREATION_SCREEN_PHASE_TITLE_PANEL_WIDTH = 0.83
CHARACTER_CREATION_SCREEN_PHASE_TITLE_PANEL_HEIGHT = 0.16
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_STARTING_X = 0.17
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_STARTING_Y = 0.16
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_WIDTH = 0.83
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_HEIGHT = 0.84
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_BUTTON_STARTING_X = .5
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_BUTTON_STARTING_Y = .5
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_BUTTON_WIDTH = .8
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_BUTTON_HEIGHT = .09
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_BUTTON_PADDING = .02
CHARACTER_CREATION_SCREEN_BUTTON_PANEL_BUTTON_FONT_SIZE = 22
CHARACTER_CREATION_SCREEN_NAVIGATION_BUTTON_WIDTH = .2
CHARACTER_CREATION_SCREEN_NAVIGATION_BUTTON_HEIGHT = .08
CHARACTER_CREATION_SCREEN_NAVIGATION_BUTTON_Y = .85
CHARACTER_CREATION_SCREEN_NAVIGATION_BUTTON_X = .5
CHARACTER_CREATION_SCREEN_NAVIGATION_BUTTON_PADDING = .05
CHARACTER_CREATION_SCREEN_NAVIGATION_BUTTON_FONT_SIZE = 22
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_FONT_SIZE = 28
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_TEXT_PADDING = .02
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_HEADER_TEXT_UNDERLINE = .02
CHARACTER_CREATION_SCREEN_RECT_BUFFER = .02
CHARACTER_CREATION_SCREEN_DISPLAY_DATA_PANEL_DESCRIPTION_FONT_SIZE = 22
CHARACTER_CREATION_SCREEN_HEADER_UNDERLINE_HEIGHT = 2

#--- Colors ---
#Standard
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLACK = (0, 0, 0)
ORANGE = (255, 100, 10)
YELLOW = (255, 255, 0)
BLUE_GREEN = (140, 150, 10)
#Themed
RICH_SOIL = (89, 61, 59)
AGED_WOOD = (181, 137, 107)
TERRACOTTA_CLAY = (195, 113, 79)
FOREST_CANOPY = (34, 87, 61)
MOSSY_STONE = (111, 129, 101)
SUNLIT_MEADOW = (153, 185, 121)
SLATE_GRAY = (83, 92, 104)
RIVER_STONE_BLUE = (122, 141, 162)
DAWN_SKY_PEACH = (252, 218, 201)
WILDFLOWER_PURPLE = (136, 119, 184)
GOLDEN_SUNBEAM = (252, 222, 112)
HEARTHFIRE_ORANGE = (221, 124, 69)
CHARCOAL_SLATE = (45, 48, 53)
BRIDGEWATER_BLUE = (90, 158, 226)
PALE_GRANITE = (205, 209, 224)
BRIGHT_LEAF = (181, 222, 154)
EMBERGLOW = (239, 155, 83)
SKYFORGE_BLUE = (117, 181, 234)
TWILIGHT_LAVENDER = (191, 178, 229)
ARCANE_ORCHID = (204, 160, 255)
SANDSTONE_OCHRE = (218, 195, 154)
RADIANT_GOLD = (255, 210, 100)
SOLAR_FLARE = (255, 245, 50)